### ISSUE TITLE
Tapping on character causes error, doesn't open Jisho

### ISSUE THREAD

**Issue by thomasmarsh** [AustinHasten/AnkiKanjiTable#4]
Using latest (2024-01-06) on macOS:

```
Traceback (most recent call last):
  File "/Users/tmarsh/Library/Application Support/Anki2/addons21/1828617820/__init__.py", line 175, in cellClicked
    cell.openLink()
  File "/Users/tmarsh/Library/Application Support/Anki2/addons21/1828617820/__init__.py", line 161, in openLink
    webbrowser.open(f'https://jisho.org/search/{self.value} %23kanji')
  File "webbrowser", line 86, in open
  File "webbrowser", line 683, in open
UnicodeEncodeError: 'ascii' codec can't encode character '\u754c' in position 40: ordinal not in range(128)
```

**Comment by AustinHasten** [comment]
Hmm, I'm not able to reproduce this. I wonder if it is Mac-specific. If you are willing and able to do some testing for me, could you try:

Add the below line to the top of KanjiTable.py
`import urllib.request`

Change line 86 or so from:
`webbrowser.open(f"https://jisho.org/search/{self.text()} %23kanji")`
to:
`webbrowser.open(f"https://jisho.org/search/{urllib.request.quote(self.text())} %23kanji")`
